targets:
  $default:
    builders:
      json_serializable|json_serializable:
        generate_for:
          - lib/shared/models/**.dart
      freezed|freezed:
        generate_for:
          - lib/shared/models/**.dart
          - lib/components/**/bloc/**.dart
          - lib/shared/bloc/**.dart
      injectable_generator|injectable_builder:
        generate_for:
          - lib/components/**/bloc/**.dart
          - lib/shared/di/**.dart
          - lib/shared/repositories/**.dart
